#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(Tetrix)

task main()
{
  int i;

  for (i = 0; i <= 256; i += 16)
  {
    servo[servo1] = i;
    nxtDisplayTextLine(3, "Servo: %d", i);
    wait1Msec(50);
  }
}
