#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////////////////////////////////////////////////////////////////////////////////////////////////
//
//                            FTC Motor Test Program
//
// A very simply program to test that the two motors connected to a HiTechnic Motor Controller
// (motor battery leads and encoder leads) are properly wired.
//
// Simply compile and download this program. Make sure the debugger "NXT Devices" window is
// open and the debugger is set for "Continuous" polling.
//
// NOw run the program and watch the debugger window. Make sure the appropriate encoder values
// are properly changed.
//    -- They should increase for forward (positive) power. And decrease for reverse (negative)
//       motor power.
//    -- The encoder values that change should correspond to the motor that is powered. Otherwise
//       the encoders are wired to the wrong ports.
//
// NOTES:
//
//  1. The orange lead on the motor encoder connector should face the "fat" side of the HiTechnic
//     motor encoder. If it is connected in the reverse direction, then the encoder values
//     will not change.
//
//  2. If the motor encoder is changing in the wrong direction, then swap the wires that connect
//     to its corresponding motor.
//
//  3. If motor is configured for "PID Speed Control" and the motor encoders are not working,
//     then the PID algorithm (which adjusts the motor power level so that it maintains a
//     constant speed will end up setting motor to either full forward or full reverse.
//
//  4. Similarly, if the motor leads need to be swapped, then "PID Speed Control" will get
//     confused and set motor to full power.
//
//  5. Because of points (4) and (5) the motors have been configured NOT to use PID speed
//     control. The configuration is done in the above "$#pragma" which have been automatically
//     inserted by the "Motors and Sensors Setup" command found on the ROBOTC main menu.
//
// If there is no response from the motors, it may be because the external battery is not
// properly connected or is fully discharged. The Hitechnic Motor Controller draws its power
// from the external battery and will not function if the battery is not connected!
// Check for satisfactory external battery operation as follows:
//
//  1. Power cycle the NXT.
//
//  2. If the top left status line of the NXT LCD does not show two battery charge status
//     graphics then the HiTechnic Motor Controller is not responding. NOTE: the dual status
//     display is only available with the ROBOTC firmware.
//
//  3. The battery graphic (icon) indicates the charge state of the battery. The graphic
//     is in the shape of a battery. A solid filled shape indicates a battery that is nearly
//     fully charged. The less filled ared in the graphic, the more the battery is discharged.
//
////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	// Stop both motors

	motor[motorD] = 0;
	motor[motorE] = 0;


	while (true)
	{

		// Run motorD (i.e. motor 1 on the Hitechnic controller) forward and then reverse

		PlaySoundFile("01.rso");   // Plays file containing audio for '1'
		motor[motorD] = 50;
		wait1Msec(2000);
		motor[motorD] = -50;
		wait1Msec(2000);
		motor[motorD] = 0;

		// Run motorE (i.e. motor 2 on the Hitechnic controller) forward and then reverse

		PlaySoundFile("02.rso"); // Plays file containing audio for '2'
		motor[motorE] = 50;
		wait1Msec(2000);
		motor[motorE] = -50;
		wait1Msec(2000);
		motor[motorE] = 0;
	}
}

//
// NOTE: ROBOTC may be unable to locate the files "01.rso" and "02.rso" to download to the NXT.
//       These files are similar to PC "WAV" files and contain the audio samples for the words
//       "one" and "two". The program will still function, but without the audio feedback.
