#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//TJoystick joystick;

void motorControlProportional()
{
  int nMotorPower;
  int nDirection;

  nMotorPower = joystick.joy1_y1;
  nDirection  = joystick.joy1_x1;
  if (nDirection < 0)
  {
    // Turn left

    motor[rightMotor] = nMotorPower; // use power settings from Y-axis
    motor[leftMotor]  = nMotorPower * (64 + nDirection) / 64;
  }
  else
  {
    // Turn right

    motor[leftMotor]  = nMotorPower; // use power settings from Y-axis
    motor[rightMotor] = nMotorPower * (64 - nDirection) / 64;
  }
}

void buttonControl()
{
  return;
}

task main()
{
  while (true)
  {
    getJoystickSettings(joystick);
    motorControlProportional();
    buttonControl();
  }
}
