#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(Tetrix)

void goForward(const int nTime)
{
  motor[leftMotor]  = 75;
  motor[rightMotor] = 75;
  wait1Msec(nTime);
}

void turnRight(const int nTime)
{
  motor[leftMotor]  = 75;
  motor[rightMotor] =  0;
  wait1Msec(nTime);
}

void turnLeft(const int nTime)
{
  motor[leftMotor]  =  0;
  motor[rightMotor] = 75;
  wait1Msec(nTime);
}

void goBackwards(const int nTime)
{
  motor[leftMotor]  = -75;
  motor[rightMotor] = -75;
  wait1Msec(nTime);
}

task main()
{
  goForward(2000);
  turnLeft(1000);
  goForward(2000);
  turnRight(500);
  goForward(500);
  goBackwards(3000);
}
