#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  float rpmD;
  float rpmE;
  long moveD;
  long moveE;
  while (true)
  {
    nMotorEncoder[motorD] = 0;
    nMotorEncoder[motorE] = 0;
    time1[T1] = 0;
    while (time1[T1] < 1000)
    {
      motor[motorD] = 100;
	    motor[motorE] = 10;
	    wait1Msec(10);
	    motor[motorD] = 10;
	    motor[motorE] = 100;
	    wait1Msec(10);
	  }
    moveD = nMotorEncoder[motorD];
    moveE = nMotorEncoder[motorE];
    rpmD = ((float) moveD) / 1440 * 60;
    rpmE = ((float) moveE) / 1440 * 60;
  }
}
